// pages/Payment/PaymentReport.js
import React, { useCallback, useContext, useState, useMemo } from "react";
import {
  ActivityIndicator, Alert, FlatList, ScrollView, StyleSheet,
  Text, TouchableOpacity, View, TextInput, Modal, Image
} from "react-native";
import { SafeAreaView } from "react-native-safe-area-context";
import { Ionicons } from "@expo/vector-icons";
import * as Print from "expo-print";
import * as Sharing from "expo-sharing";
import * as ImagePicker from "expo-image-picker";
import { useFocusEffect } from "@react-navigation/native";
import { DataContext } from "../../context";

const METHODS = ["upi", "cash", "card", "bank", "wallet"];

export default function PaymentReport() {
  const { apiGet, apiDelete, apiPut } = useContext(DataContext);
  const [payments, setPayments] = useState([]);
  const [loading, setLoading] = useState(false);
  const [query, setQuery] = useState("");
  const [preview, setPreview] = useState(null);

  // edit state
  const [editItem, setEditItem] = useState(null);
  const [newImageUri, setNewImageUri] = useState(null);
  const [saving, setSaving] = useState(false);

  const formatINR = (n) => (Number(n) || 0).toLocaleString("en-IN", { maximumFractionDigits: 2 });

  const loadPayments = useCallback(async () => {
    //    setLoading(true);
    try {
      const res = await apiGet("/payments");
      setPayments(res?.success && Array.isArray(res.data) ? res.data : []);
    } catch {
      setPayments([]);
    } finally {
      setLoading(false);
    }
  }, [apiGet]);

  useFocusEffect(useCallback(() => { loadPayments(); }, [loadPayments]));

  // search + totals
  const filtered = useMemo(() => {
    const q = query.trim().toLowerCase();
    if (!q) return payments;
    return payments.filter((p) =>
      (p.clientName || "").toLowerCase().includes(q) ||
      (p.clientPhone || "").toLowerCase().includes(q) ||
      (p.txId || "").toLowerCase().includes(q)
    );
  }, [payments, query]);

  const totalAmount = useMemo(
    () => filtered.reduce((sum, p) => sum + (Number(p.amount) || 0), 0),
    [filtered]
  );

  // Admin PDF (includes client info + image)
  const buildReceiptHtml = (item) => `
   <html>
     <head>
       <meta charset="UTF-8" />
       <style>
         body {
           font-family: Arial, sans-serif;
           background-color: #0f172a;
           color: #e6eefc;
           padding: 10px;
           margin: 0;
         }

//         .container {
//           background-color: #0b1220;
//           border: 1px solid #1f2a44;
//           border-radius: 16px;
//           max-width: 600px;
//           margin: 0 auto;
//           padding: 24px;
//           box-shadow: 0 4px 10px rgba(0,0,0,0.3);
//         }

         h2 {
           text-align: center;
           color: #ffffff;
           font-size: 22px;
           margin-bottom: 16px;
           border-bottom: 1px solid #1f2a44;
           padding-bottom: 8px;
         }

         .image-wrapper {
           text-align: center;
           margin-bottom: 20px;
         }

         .image-wrapper img {
           width: 100%;
           max-height: 240px;
           border-radius: 12px;
           object-fit: cover;
           border: 1px solid #1f2a44;
         }

         table {
           width: 100%;
           border-collapse: collapse;
         }

         td {
           padding: 8px 6px;
           vertical-align: top;
         }

         td.label {
           color: #9fb1cc;
           font-weight: 600;
           width: 40%;
         }

         td.value {
           color: #e6eefc;
           text-align: right;
           font-weight: 700;
         }

         .footer {
           text-align: center;
           color: #9fb1cc;
           margin-top: 30px;
           font-size: 12px;
         }
       </style>
     </head>
     <body>
       <div class="container">
         ${item.imageUrl
      ? `<div class="image-wrapper"><img src="${item.imageUrl}" /></div>`
      : ""}
         <h2>Payment Details</h2>
         <table>
           <tr><td class="label">Client</td><td class="value">${item.clientName || "-"}</td></tr>
           <tr><td class="label">Phone</td><td class="value">${item.clientPhone || "-"}</td></tr>
           <tr><td class="label">Source</td><td class="value">${item.source || "-"}</td></tr>
           <tr><td class="label">Amount</td><td class="value">₹${formatINR(item.amount)}</td></tr>
           <tr><td class="label">Txn ID</td><td class="value">${item.txId || "-"}</td></tr>
           <tr><td class="label">Method</td><td class="value">${(item.method || "").toUpperCase()}</td></tr>
           <tr><td class="label">Date</td><td class="value">${new Date(item.createdAt).toLocaleString()}</td></tr>
         </table>
         <div class="footer">Generated by Payment System</div>
       </div>
     </body>
   </html>
 `;

  const downloadPayment = async (item) => {
    try {
      const html = buildReceiptHtml(item);
      const { uri } = await Print.printToFileAsync({ html });
      if (await Sharing.isAvailableAsync()) await Sharing.shareAsync(uri);
    } catch {
      Alert.alert("Error", "Failed to generate PDF");
    }
  };

  const pickNewImage = useCallback(async () => {
    const perm = await ImagePicker.requestMediaLibraryPermissionsAsync();
    if (perm.status !== "granted") return Alert.alert("Permission required", "Allow Photo Library access.");
    const result = await ImagePicker.launchImageLibraryAsync({
      mediaTypes: ImagePicker.MediaTypeOptions.Images, allowsEditing: true, quality: 0.9,
    });
    if (!result.canceled && result.assets?.length) setNewImageUri(result.assets[0].uri);
  }, []);


  // ✅ Save (Admin Edit)
  const saveEdit = useCallback(async () => {
    if (!editItem) return;
    setSaving(true);

    try {
      const payload = {
        clientName: editItem.clientName?.trim() || "",
        clientPhone: editItem.clientPhone?.trim() || "",
        source: editItem.source?.trim() || "",
        amount: String(editItem.amount ?? ""),
        txId: editItem.txId?.trim() || "",
        method: editItem.method?.trim() || "",
      };

      let res;

      if (newImageUri) {
        // FormData upload for image replacement
        const fd = new FormData();
        Object.entries(payload).forEach(([k, v]) => fd.append(k, v));
        fd.append("paymentImage", {
          uri: newImageUri,
          name: `payment_${Date.now()}.jpg`,
          type: "image/jpeg",
        });

        res = await apiPut(`/payments/${editItem._id}`, fd, {
          "Content-Type": "multipart/form-data",
        });
      } else {
        // Normal text update
        res = await apiPut(`/payments/${editItem._id}`, payload);
      }

      if (res?.success) {
        Alert.alert("✅ Updated", "Payment updated successfully");
        setEditItem(null);
        setNewImageUri(null);
        loadPayments();
      } else {
        Alert.alert("❌ Error", res?.message || "Failed to update payment");
      }
    } catch (err) {
      Alert.alert("Error", "Update failed: " + err.message);
    } finally {
      setSaving(false);
    }
  }, [apiPut, editItem, newImageUri, loadPayments]);



  // ✅ Delete (Admin / User)
  const confirmDelete = (id) => {
    Alert.alert("Delete Payment", "Are you sure? This cannot be undone.", [
      { text: "Cancel", style: "cancel" },
      {
        text: "Delete",
        style: "destructive",
        onPress: async () => {
          try {
            const res = await apiDelete(`/payments/${id}`);
            if (res?.success) {
              Alert.alert("Deleted", "Payment deleted successfully");
              loadPayments();
            } else {
              Alert.alert("Error", res?.message || "Failed to delete");
            }
          } catch (err) {
            Alert.alert("Error", "Delete failed: " + err.message);
          }
        },
      },
    ]);
  };

  return (
    <SafeAreaView style={styles.safe}>
      <View style={styles.headerColumn}>
        <Text style={styles.title}>
          🧾 Admin Payment Report
        </Text>

        <Text style={styles.subTitle}>
          Total: ₹{formatINR(totalAmount)} ({filtered.length})
        </Text>

        <View style={styles.searchBox}>
          <Ionicons name="search-outline" size={16} color="#9fb1cc" />
          <TextInput
            style={styles.searchInput}
            value={query}
            onChangeText={setQuery}
            placeholder="Search client, phone, Txn ID"
            placeholderTextColor="#7a8ca6"
          />
        </View>
      </View>

      {loading ? (
        <ActivityIndicator color="#60a5fa" style={{ marginTop: 30 }} />
      ) : (
        <ScrollView horizontal showsHorizontalScrollIndicator={false}>
          <View style={{ minWidth: 1024 }}>
            <View style={styles.tableHeader}>
              {["#", "Client", "Phone", "Amount", "Txn ID", "Method", "Source", "Date", "Actions"].map((h) => (
                <Text key={h} style={styles.tableHeaderText}>{h}</Text>
              ))}
            </View>
            <FlatList
              keyboardShouldPersistTaps="handled"
              keyboardDismissMode="interactive"
              data={filtered}
              keyExtractor={(item) => item._id}
              renderItem={({ item, index }) => (
                <View style={styles.tableRow}>
                  <Text style={styles.cell}>{index + 1}</Text>
                  <Text style={styles.cell}>{item.clientName}</Text>
                  <Text style={styles.cell}>{item.clientPhone}</Text>
                  <Text style={styles.cell}>₹{formatINR(item.amount)}</Text>
                  <Text style={styles.cell}>{item.txId}</Text>
                  <Text style={styles.cell}>{(item.method || "").toUpperCase()}</Text>
                  <Text style={styles.cell}>{item.source}</Text>
                  <Text style={styles.cell}>{new Date(item.createdAt).toLocaleDateString()}</Text>
                  <View style={[styles.cell, { flexDirection: "row", gap: 10 }]}>
                    <TouchableOpacity onPress={() => setPreview(item)}>
                      <Ionicons name="eye-outline" size={18} color="#60a5fa" />
                    </TouchableOpacity>
                    <TouchableOpacity onPress={() => downloadPayment(item)}>
                      <Ionicons name="download-outline" size={18} color="#a7f3d0" />
                    </TouchableOpacity>
                    <TouchableOpacity onPress={() => { setEditItem(item); setNewImageUri(null); }}>
                      <Ionicons name="create-outline" size={18} color="#facc15" />
                    </TouchableOpacity>
                    <TouchableOpacity onPress={() => confirmDelete(item._id)}>
                      <Ionicons name="trash-outline" size={18} color="#f87171" />
                    </TouchableOpacity>
                  </View>
                </View>
              )}
            />
          </View>
        </ScrollView>
      )}

      {/* View Modal (full details) */}
      <Modal visible={!!preview} transparent animationType="slide" onRequestClose={() => setPreview(null)}>
        <View style={styles.backdrop}>
          <View style={styles.modal}>
            {preview?.imageUrl ? <Image source={{ uri: preview.imageUrl }} style={styles.previewImg} /> : null}
            <Text style={styles.modalTitle}>Payment Details</Text>
            {[
              ["Client", preview?.clientName],
              ["Phone", preview?.clientPhone],
              ["Source", preview?.source],
              ["Amount", `₹${formatINR(preview?.amount)}`],
              ["Txn ID", preview?.txId],
              ["Method", (preview?.method || "").toUpperCase()],
              ["Date", new Date(preview?.createdAt).toLocaleString()],
            ].map(([k, v]) => (
              <View key={k} style={styles.row}>
                <Text style={styles.label}>{k}</Text>
                <Text style={styles.value}>{v}</Text>
              </View>
            ))}
            <TouchableOpacity style={styles.closeBtn} onPress={() => setPreview(null)}>
              <Text style={styles.closeText}>Close</Text>
            </TouchableOpacity>
          </View>
        </View>
      </Modal>

      {/* Edit Modal (admin can update all fields + replace image) */}
      <Modal visible={!!editItem} transparent animationType="slide" onRequestClose={() => setEditItem(null)}>
        <View style={styles.backdrop}>
          <View style={styles.modal}>
            <Text style={styles.modalTitle}>Edit Payment</Text>
            {["clientName", "clientPhone", "source", "amount", "txId"].map((field) => (
              <View key={field} style={{ marginBottom: 8 }}>
                <Text style={styles.label}>{field}</Text>
                <TextInput
                  style={styles.input}
                  value={String(editItem?.[field] ?? "")}
                  onChangeText={(v) => setEditItem((p) => ({ ...p, [field]: v }))}
                  keyboardType={field === "amount" ? "decimal-pad" : "default"}
                />
              </View>
            ))}
            <Text style={styles.label}>method</Text>
            <ScrollView horizontal contentContainerStyle={{ gap: 8, paddingVertical: 6 }}>
              {METHODS.map((m) => {
                const active = (editItem?.method || "") === m;
                return (
                  <TouchableOpacity
                    key={m}
                    onPress={() => setEditItem((p) => ({ ...p, method: m }))}
                    style={[styles.chip, active && styles.chipActive]}>
                    <Text style={[styles.chipText, active && styles.chipTextActive]}>{m.toUpperCase()}</Text>
                  </TouchableOpacity>
                );
              })}
            </ScrollView>

            {/* Image replace */}
            <Text style={[styles.label, { marginTop: 8 }]}>Receipt Image</Text>
            <View style={{ flexDirection: "row", alignItems: "center", gap: 10 }}>
              <Image
                source={{ uri: newImageUri || editItem?.imageUrl }}
                style={{ width: 80, height: 80, borderRadius: 8, borderWidth: 1, borderColor: "#1f2a44" }}
              />
              <TouchableOpacity style={styles.saveBtn} onPress={pickNewImage}>
                <Text style={styles.closeText}>{newImageUri ? "Change Image" : "Replace Image"}</Text>
              </TouchableOpacity>
            </View>

            <View style={{ flexDirection: "row", gap: 10, marginTop: 12 }}>
              <TouchableOpacity style={styles.saveBtn} onPress={saveEdit} disabled={saving}>
                <Text style={styles.closeText}>{saving ? "Saving..." : "Save"}</Text>
              </TouchableOpacity>
              <TouchableOpacity style={styles.closeBtn} onPress={() => { setEditItem(null); setNewImageUri(null); }}>
                <Text style={styles.closeText}>Cancel</Text>
              </TouchableOpacity>
            </View>
          </View>
        </View>
      </Modal>
    </SafeAreaView>
  );
}

/* ---------- Styles ---------- */
const styles = StyleSheet.create({
  safe: { flex: 1, backgroundColor: "#0b1220", padding: 10 },
  header: { flexDirection: "row", justifyContent: "space-between", alignItems: "center", marginBottom: 6 },
  title: { color: "#fff", fontSize: 18, fontWeight: "800" },
  searchBox: { flexDirection: "row", alignItems: "center", backgroundColor: "#0f172a", borderWidth: 1, borderColor: "#1f2a44", borderRadius: 8, paddingHorizontal: 10 },
  searchInput: { color: "#e6eefc", padding: 8, flex: 1 },
  tableHeader: { flexDirection: "row", backgroundColor: "#1e293b" },
  tableHeaderText: { flex: 1, color: "#cbd5e1", fontWeight: "700", padding: 10, minWidth: 120 },
  tableRow: { flexDirection: "row", borderBottomWidth: 1, borderColor: "#1f2a44", backgroundColor: "#0f172a" },
  cell: { flex: 1, color: "#e6eefc", padding: 10, minWidth: 120 },
  backdrop: { flex: 1, backgroundColor: "rgba(0,0,0,0.6)", justifyContent: "center", padding: 20 },
  modal: { backgroundColor: "#0f172a", borderRadius: 12, borderWidth: 1, borderColor: "#1f2a44", padding: 16 },
  modalTitle: { color: "#fff", fontWeight: "800", fontSize: 18, marginBottom: 10 },
  previewImg: { width: "100%", height: 200, borderRadius: 10, marginBottom: 10 },
  row: { flexDirection: "row", justifyContent: "space-between", marginBottom: 6 },
  label: { color: "#9fb1cc" },
  value: { color: "#e6eefc", fontWeight: "600" },
  closeBtn: { backgroundColor: "#334155", padding: 10, borderRadius: 8, alignItems: "center", flex: 1 },
  saveBtn: { backgroundColor: "#2563eb", padding: 10, borderRadius: 8, alignItems: "center", flex: 1 },
  closeText: { color: "#fff", fontWeight: "700" },
  input: { backgroundColor: "#0b1220", color: "#e6eefc", borderWidth: 1, borderColor: "#1f2a44", borderRadius: 8, padding: 8, marginBottom: 8 },
  chip: { borderWidth: 1, borderColor: "#1f2a44", paddingVertical: 6, paddingHorizontal: 10, borderRadius: 999 },
  chipActive: { backgroundColor: "#1d4ed8", borderColor: "#1d4ed8" },
  chipText: { color: "#b8c7e6", fontSize: 12, fontWeight: "600" },
  chipTextActive: { color: "#fff" },
  headerColumn: {
    marginBottom: 10,
    flexDirection: "column",
    justifyContent: "flex-start",
    alignItems: "flex-start",
  },
  subTitle: {
    color: "#9fb1cc",
    fontSize: 20,
    marginBottom: 16,
    marginTop: 16,
    fontWeight: "900"
  },
});
